### ISSUE TITLE
no results in spreadsheet& no loading in terminal... 

### ISSUE THREAD

**Issue by wilroy** [Taskulu/tweelead#4] opened 2015-02-24 10:20 UTC
hello there, I'm trying your code and i've got nothing when launching the node index command. I've followed all the steps (even the one concerning the google spreadsheet that is missing) and there's nothing, a second after the 3rd command, my terminal is ready to receive a new command, no loading or else... Did you faced such issue?

**Comment by farhadhf** [comment] 2015-02-25 14:26
Hey, I didn't have this problem and couldn't reproduce it today when I tested. There have been some changes today, can you try again?

Btw, do you get any errors or it just dies without saying anything?

**Comment by wilroy** [comment] 2015-02-25 18:01
Thank you for your answer. I'll try again tomorrow, I don't get any errors I lauch the node index command and one second later, a line appears waiting for the next command...

**Comment by wilroy** [comment] 2015-03-01 11:39
Hello, that does work now! I've tweet loading into my terminal, but they don't load into the spreasheet... Event if, I've put the doc key into the config.ini doc, I've got nothing... Any idea?

**Comment by jesseorndorff** [comment] 2015-05-26 07:53
I also can't seem to get it writing to Google Docs. No idea why. Everything else seems fine.

**Comment by alexiskattan** [comment] 2015-06-17 01:33
same as @jesseorndorff.  The program is writing to the console but nothing is saved in the spreadsheet.

**Comment by alexiskattan** [comment] 2015-06-17 02:34
https://github.com/Taskulu/tweelead/pull/8

**Comment by farhadhf** [comment] 2015-06-17 07:18
Thanks @alexiskattan, I just merged your pull request. Closing this issue.

**Closed as completed by farhadhf** 2015-06-17 07:18 UTC
